prev_file_date: '20240107'
current_date: '2024-02-27' 
timeline_end: '2024-06-30' # generally set to end of current/next season
# data_dir: '/Users/alice/Dropbox/Projects/hockey_db_data/'
data_dir: '/Users/alicelai/Dropbox/Projects/hockey_db_data/'